name: Update Config

on:
  repository_dispatch:
    types: [update-config]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update config.json
        run: |
          CONFIG_FILE='config.json'
          if [ -f "$CONFIG_FILE" ]; then
            CURRENT_ROUND=$(jq '.round' $CONFIG_FILE)
            NEW_ROUND=$((CURRENT_ROUND + 1))
            jq --argjson round "$NEW_ROUND" '.round = $round' $CONFIG_FILE > temp.json
            mv temp.json $CONFIG_FILE
            git config --global user.name 'github-actions'
            git config --global user.email 'actions@github.com'
            git add $CONFIG_FILE
            git commit -m 'Increment round number'
            git push
          else
            echo "$CONFIG_FILE not found!"
            exit 1
          fi
